import type { APIRoute } from 'astro';
import { currentSite } from '../lib/site';
import { readBrandFile } from '../lib/brand-files';

export const prerender = true;
// Home-screen icon for iOS and iPadOS.
// Generated by scripts/generate-brand-assets.mjs.
export const GET: APIRoute = () =>
  new Response(readBrandFile(currentSite(import.meta.env.PUBLIC_SITE_KEY), 'apple-touch-icon.png'), {
    headers: { 'Content-Type': 'image/png' }
  });
