import type { APIRoute } from 'astro';
import { currentSite } from '../lib/site';
import { readBrandFile } from '../lib/brand-files';

export const prerender = true;
// Fallback favicon for browsers without SVG favicon support. Also stops the 403 on /favicon.ico.
// Generated by scripts/generate-brand-assets.mjs.
export const GET: APIRoute = () =>
  new Response(readBrandFile(currentSite(import.meta.env.PUBLIC_SITE_KEY), 'favicon.ico'), {
    headers: { 'Content-Type': 'image/x-icon' }
  });
