import type { APIRoute } from 'astro';
import { currentSite } from '../lib/site';
import { readBrandFile } from '../lib/brand-files';

export const prerender = true;
// Open Graph and Twitter Card preview image, 1200 x 630.
// Generated by scripts/generate-brand-assets.mjs.
export const GET: APIRoute = () =>
  new Response(readBrandFile(currentSite(import.meta.env.PUBLIC_SITE_KEY), 'og-image.png'), {
    headers: { 'Content-Type': 'image/png' }
  });
